# SPDX-FileCopyrightText: 2025 IObundle
#
# SPDX-License-Identifier: MIT

name: CI

# Set default shell as interactive (source ~/.bashrc)
defaults:
  run:
    shell: bash -ieo pipefail {0}

# Run only one instance of this workflow at a time
# cancel-in-progress: stop running workflow and run latest instead
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  # Allow manual workflow runs
  workflow_dispatch:

jobs:

  pc-emul:
    runs-on: self-hosted
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Clean untracked files and directories (like old submodules)
        run: git clean -ffdx
      - name: run test
        run: make pc-emul-test

  simulation:
    runs-on: self-hosted
    timeout-minutes: 30
    # run even if previous job failed
    if: ${{ !cancelled() }}
    needs: [ pc-emul ]
  
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Clean untracked files and directories (like old submodules)
        run: git clean -ffdx
      - name: run test
        run: make sim-test
  
  cyclonev:
    runs-on: self-hosted
    timeout-minutes: 60
    if: ${{ !cancelled() }}
    needs: [ simulation ]
  
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Clean untracked files and directories (like old submodules)
        run: git clean -ffdx
      - name: init mem and no ext mem
        run: make fpga-run BOARD=cyclonev_gt_dk USE_INTMEM=1 USE_EXTMEM=0 INIT_MEM=1
      - name: no init mem and ext mem
        run: make fpga-run BOARD=cyclonev_gt_dk USE_INTMEM=0 USE_EXTMEM=1 INIT_MEM=0
  
  ku040:
    runs-on: self-hosted
    timeout-minutes: 90
    if: ${{ !cancelled() }}
    needs: [ simulation ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Clean untracked files and directories (like old submodules)
        run: git clean -ffdx
      - name: init mem and no ext mem
        run: make fpga-run BOARD=aes_ku040_db_g USE_INTMEM=1 USE_EXTMEM=0 INIT_MEM=1
      - name: no init mem and ext mem
        run: make fpga-run BOARD=aes_ku040_db_g USE_INTMEM=0 USE_EXTMEM=1 INIT_MEM=0

  doc:
    runs-on: self-hosted
    timeout-minutes: 60
    if: ${{ !cancelled() }}
    needs: [ cyclonev ]
  
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Clean untracked files and directories (like old submodules)
        run: git clean -ffdx
      - name: doc test
        run: make doc-test

  reuse:
    runs-on: self-hosted
    timeout-minutes: 3
    if: ${{ !cancelled() }}
    needs: [ doc ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Clean untracked files and directories (like old submodules)
        run: git clean -ffdx
      - name: Check compliance with REUSE specification
        run: nix-shell --run "reuse lint"
